services:
  app:
    build: .
    container_name: wallet-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://naveen-94-sknaveenvj-a768.i.aivencloud.com:26485/defaultdb?ssl-mode=REQUIRED
      SPRING_DATASOURCE_USERNAME: avnadmin
      SPRING_DATASOURCE_PASSWORD: AVNS_sflxthwhMCP-IcuvjDr
